/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author usuario
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        tfCampo = new javax.swing.JTextField();
        bDel = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bCE = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        bMasMenos = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bPunto = new javax.swing.JButton();
        bMas = new javax.swing.JButton();
        bMenos = new javax.swing.JButton();
        bPor = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        bIgual = new javax.swing.JButton();
        bSin = new javax.swing.JButton();
        bCos = new javax.swing.JButton();
        bTan = new javax.swing.JButton();
        bRaiz = new javax.swing.JButton();
        bPot = new javax.swing.JButton();
        bConvertir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taConv = new javax.swing.JTextArea();
        lOpciones = new javax.swing.JComboBox<>();
        bLimpiar = new javax.swing.JButton();
        tfCampoConver = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(350, 450));

        tfCampo.setEditable(false);
        tfCampo.setBackground(new java.awt.Color(255, 255, 255));
        tfCampo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCampo.setText("0");
        tfCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoActionPerformed(evt);
            }
        });

        bDel.setText("Del");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });

        bC.setText("C");
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bCE.setText("CE");
        bCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCEActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        bMasMenos.setText("+/-");
        bMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasMenosActionPerformed(evt);
            }
        });

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bPunto.setText(",");
        bPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuntoActionPerformed(evt);
            }
        });

        bMas.setText("+");
        bMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasActionPerformed(evt);
            }
        });

        bMenos.setText("-");
        bMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosActionPerformed(evt);
            }
        });

        bPor.setText("*");
        bPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPorActionPerformed(evt);
            }
        });

        bDiv.setText("/");
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });

        bIgual.setText("=");
        bIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIgualActionPerformed(evt);
            }
        });

        bSin.setText("Sin");
        bSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSinActionPerformed(evt);
            }
        });

        bCos.setText("Cos");
        bCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCosActionPerformed(evt);
            }
        });

        bTan.setText("Tan");
        bTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTanActionPerformed(evt);
            }
        });

        bRaiz.setText("Sqrt");
        bRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRaizActionPerformed(evt);
            }
        });

        bPot.setText("x^2");
        bPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPotActionPerformed(evt);
            }
        });

        bConvertir.setText("Convertir");
        bConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConvertirActionPerformed(evt);
            }
        });

        taConv.setEditable(false);
        taConv.setColumns(20);
        taConv.setRows(5);
        jScrollPane1.setViewportView(taConv);

        lOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Longitud", "Masa", "Temperatura" }));

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        tfCampoConver.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.#################################################################################################"))));
        tfCampoConver.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCampoConver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoConverActionPerformed(evt);
            }
        });
        tfCampoConver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCampoConverKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCampo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bMas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bPor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(lOpciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCampoConver))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(bConvertir)
                        .addGap(18, 18, 18)
                        .addComponent(bLimpiar)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(tfCampoConver))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bCE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bMas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bPor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bSin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lOpciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bPot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bConvertir)
                            .addComponent(bLimpiar))))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        if (tfCampo.getText().length() > 0) {
            tfCampo.setText((tfCampo.getText().substring(0, tfCampo.getText().length() - 1).length() > 0 ? tfCampo.getText().substring(0, tfCampo.getText().length() - 1) : "0"));
        }
        
    }//GEN-LAST:event_bDelActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        // TODO add your handling code here:
        primerNumero = 0;
        segundoNumero = 0;
        operaciones = "";
        tfCampo.setText("0");
        
    }//GEN-LAST:event_bCActionPerformed

    private void bCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCEActionPerformed
        // TODO add your handling code here:
        tfCampo.setText("0");
        segundoNumero = 0;

    }//GEN-LAST:event_bCEActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b9.getText());
        } else {
            tfCampo.setText(b9.getText());
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b7.getText());
        } else {
            tfCampo.setText(b7.getText());
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b8.getText());
        } else {
            tfCampo.setText(b8.getText());
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b6.getText());
        } else {
            tfCampo.setText(b6.getText());
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b4.getText());
        } else {
            tfCampo.setText(b4.getText());
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b5.getText());
        } else {
            tfCampo.setText(b5.getText());
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b3.getText());
        } else {
            tfCampo.setText(b3.getText());
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b1.getText());
        } else {
            tfCampo.setText(b1.getText());
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b2.getText());
        } else {
            tfCampo.setText(b2.getText());
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void bMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasMenosActionPerformed
        // TODO add your handling code here:
        tfCampo.setText(Double.parseDouble(tfCampo.getText()) * (-1) + "");
    }//GEN-LAST:event_bMasMenosActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().equals("0")) && (!tfCampo.getText().equals("Infinity"))) {
            tfCampo.setText(tfCampo.getText() + b0.getText());
        } else {
            tfCampo.setText(b0.getText());
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void bPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuntoActionPerformed
        // TODO add your handling code here:
        if ((!tfCampo.getText().contains(bPunto.getText()))) {
            
            tfCampo.setText(tfCampo.getText() + bPunto.getText());
        } else {
            tfCampo.setText(bPunto.getText());
        }
    }//GEN-LAST:event_bPuntoActionPerformed

    private void bMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(tfCampo.getText().replace(',', '.'));
        operaciones = bMas.getText();
        tfCampo.setText("0");
    }//GEN-LAST:event_bMasActionPerformed

    private void bMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(tfCampo.getText().replace(',', '.'));
        operaciones = bMenos.getText();
        tfCampo.setText("0");
    }//GEN-LAST:event_bMenosActionPerformed

    private void bPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPorActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(tfCampo.getText().replace(',', '.'));
        operaciones = bPor.getText();
        tfCampo.setText("0");
    }//GEN-LAST:event_bPorActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(tfCampo.getText().replace(',', '.'));
        operaciones = bDiv.getText();
        tfCampo.setText("0");
    }//GEN-LAST:event_bDivActionPerformed

    private void bIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIgualActionPerformed
        // TODO add your handling code here:
        segundoNumero = Double.parseDouble(tfCampo.getText().replace(',', '.'));
        if (operaciones.equals(bMas.getText())) {
            tfCampo.setText(((primerNumero + segundoNumero) + "").replace('.', ','));
        } else {
            if (operaciones.equals(bMenos.getText())) {
                tfCampo.setText(((primerNumero - segundoNumero) + "").replace('.', ','));
            } else {
                if (operaciones.equals(bPor.getText())) {
                    tfCampo.setText(((primerNumero * segundoNumero) + "").replace('.', ','));
                } else {
                    if (operaciones.equals(bDiv.getText())) {
                       
                            tfCampo.setText(((primerNumero / segundoNumero) + "").replace('.', ','));
                        
                        
                    }
                }
            }
        }
        primerNumero = 0;
        segundoNumero = 0;
        operaciones = "";
        
    }//GEN-LAST:event_bIgualActionPerformed

    private void bSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSinActionPerformed
        // TODO add your handling code here:
        tfCampo.setText((Math.sin(Double.parseDouble(tfCampo.getText().replace(',', '.'))) + "").replace('.', ','));
    }//GEN-LAST:event_bSinActionPerformed

    private void bCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCosActionPerformed
        // TODO add your handling code here:
        tfCampo.setText((Math.cos(Double.parseDouble(tfCampo.getText().replace(',', '.'))) + "").replace('.', ','));
    }//GEN-LAST:event_bCosActionPerformed

    private void bTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTanActionPerformed
        // TODO add your handling code here:
        tfCampo.setText((Math.tan(Double.parseDouble(tfCampo.getText().replace(',', '.'))) + "").replace('.', ','));
    }//GEN-LAST:event_bTanActionPerformed

    private void bRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRaizActionPerformed
        // TODO add your handling code here:
        tfCampo.setText((Math.sqrt(Double.parseDouble(tfCampo.getText())) + "").replace('.', ','));
    }//GEN-LAST:event_bRaizActionPerformed

    private void bPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPotActionPerformed
        // TODO add your handling code here:
        tfCampo.setText((Math.pow(Double.parseDouble(tfCampo.getText()), 2) + "").replace('.', ','));
    }//GEN-LAST:event_bPotActionPerformed

    private void bConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConvertirActionPerformed
        // TODO add your handling code here:
        ca = new CalculadoraConversion(Double.parseDouble(tfCampoConver.getText().replace(',', '.')));
        String resultado = "";
        if(lOpciones.getSelectedItem().equals("Longitud")){
            resultado += "m -> in\t" + ca.MetroIn();
            resultado += "\nm -> cm\t" + ca.MetrosCm();
            resultado += "\nm -> Km\t" + ca.MetrosKm();
            resultado += "\nm -> yd\t" + ca.MetrosYd();
            resultado += "\nm -> ft\t" + ca.Metrosft();
            resultado += "\ncm -> m\t" + ca.CmMetros();
            resultado += "\ncm -> in\t" + ca.CmIn();
            resultado += "\ncm -> Km\t" + ca.CmKm();
            resultado += "\ncm -> yd\t" + ca.CmYd();
            resultado += "\ncm -> ft\t" + ca.CmFt();
            resultado += "\nKm -> m\t" + ca.KmMetro();
            resultado += "\nKm -> in\t" + ca.KmIn();
            resultado += "\nKm -> cm\t" + ca.KmCm();
            resultado += "\nKm -> yd\t" + ca.KmYd();
            resultado += "\nKm -> ft\t" + ca.Kmft();
            resultado += "\nin -> m\t" + ca.InMeTros();
            resultado += "\nin -> cm\t" + ca.Incm();
            resultado += "\nin -> Km\t" + ca.InKm();
            resultado += "\nin -> yd\t" + ca.InYd();
            resultado += "\nin -> ft\t" + ca.InFt();
            resultado += "\nft -> m\t" + ca.FtMetro();
            resultado += "\nft -> cm\t" + ca.FtCm();
            resultado += "\nft -> Km\t" + ca.FtKm();
            resultado += "\nft -> yd\t" + ca.FtYd();
            resultado += "\nft -> in\t" + ca.Ftin();
            resultado += "\nyd -> m\t" + ca.YdMetros();
            resultado += "\nyd -> cm\t" + ca.YdCm();
            resultado += "\nyd -> Km\t" + ca.YdKm();
            resultado += "\nyd -> ft\t" + ca.YdFt();
            resultado += "\nyd -> in\t" + ca.YdIn();
            
        } else {
            if (lOpciones.getSelectedItem().equals("Masa")) {
                resultado += "Kg -> g\t" + ca.KgG();
                resultado += "\nKg -> lb\t" + ca.KgLb();
                resultado += "\nKg -> t\t" + ca.KgT();
                resultado += "\ng -> Kg\t" + ca.GKg();
                resultado += "\ng -> lb\t" + ca.GLb();
                resultado += "\ng -> t\t" + ca.Gt();
                resultado += "\nt -> Kg\t" + ca.TKg();
                resultado += "\nt -> g\t" + ca.TG();
                resultado += "\nt -> lb\t" + ca.Tlb();
                
            } else {
                if (lOpciones.getSelectedItem().equals("Temperatura")) {
                    resultado += "°C -> °F\t" + ca.Celciusfahrenheit();
                    resultado += "\n°C -> K\t" + ca.CelciusKelvin();
                    resultado += "\n°F -> K\t" + ca.Fahrenheitkelvin();
                    resultado += "\n°F -> °C\t" + ca.FahrenheiCelcius();
                    resultado += "\nK -> °C\t" + ca.KelvinCelcius();
                    resultado += "\nK -> °F\t" + ca.KelvinFahrenheit();
                }
                
            }
        }
        taConv.setText(resultado);
        
    }//GEN-LAST:event_bConvertirActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        tfCampoConver.setText("");
        taConv.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void tfCampoConverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoConverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoConverActionPerformed

    private void tfCampoConverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCampoConverKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/) &&
         (caracter != ','))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_tfCampoConverKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bC;
    private javax.swing.JButton bCE;
    private javax.swing.JButton bConvertir;
    private javax.swing.JButton bCos;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bIgual;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bMas;
    private javax.swing.JButton bMasMenos;
    private javax.swing.JButton bMenos;
    private javax.swing.JButton bPor;
    private javax.swing.JButton bPot;
    private javax.swing.JButton bPunto;
    private javax.swing.JButton bRaiz;
    private javax.swing.JButton bSin;
    private javax.swing.JButton bTan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lOpciones;
    private javax.swing.ButtonGroup rbGroup;
    private javax.swing.JTextArea taConv;
    private javax.swing.JTextField tfCampo;
    private javax.swing.JFormattedTextField tfCampoConver;
    // End of variables declaration//GEN-END:variables
    private double primerNumero;
    private double segundoNumero;
    private String operaciones;
    private  CalculadoraConversion ca;
    
}
